#!/usr/bin/env python3
"""Verify an existing GitHub release against the local artifact and export site metadata.

Read-only network access: this command never publishes a release or deploys a site.
"""
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys
from urllib.request import Request, urlopen
from release_metadata import sha256, validate


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--release', type=Path, required=True, help='Local release.json generated by scripts/release.py')
    parser.add_argument('--repository', default='Liugq5713/jotway')
    parser.add_argument('--tag', required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    if not re.fullmatch(r'[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+', args.repository):
        raise ValueError('Invalid repository.')
    if not re.fullmatch(r'v\d+\.\d+\.\d+', args.tag):
        raise ValueError('Tag must be vMAJOR.MINOR.PATCH.')
    record = json.loads(args.release.read_text())
    if record['version'] != args.tag[1:]:
        raise ValueError('Tag does not match the artifact version.')
    if Path(record['file']).name != record['file']:
        raise ValueError('Artifact filename must not contain a directory.')
    artifact = args.release.parent / record['file']
    if artifact.stat().st_size != record['bytes'] or sha256(artifact) != record['sha256']:
        raise ValueError('Local artifact size/checksum does not match release.json.')
    response = subprocess.check_output(['gh', 'api', f'repos/{args.repository}/releases/tags/{args.tag}'], text=True)
    release = json.loads(response)
    if release['draft'] or release['prerelease'] or not release['published_at']:
        raise ValueError('Only a published, stable release may become the site download.')
    assets = [asset for asset in release['assets'] if asset['name'] == record['file'] and asset['state'] == 'uploaded']
    if len(assets) != 1 or assets[0]['size'] != record['bytes']:
        raise ValueError('The published release must contain exactly one matching artifact.')
    asset = assets[0]
    digest = asset.get('digest')
    if digest and digest != 'sha256:' + record['sha256']:
        raise ValueError('GitHub artifact digest does not match the local artifact.')
    # Read the public URL without auth to prove that users can download the same bytes.
    request = Request(asset['browser_download_url'], headers={'User-Agent': 'Jotway-release-verifier'})
    remote_digest, size = hashlib.sha256(), 0
    with urlopen(request, timeout=90) as remote:
        for chunk in iter(lambda: remote.read(1024 * 1024), b''):
            size += len(chunk)
            if size > record['bytes']:
                raise ValueError('Remote artifact is larger than the local artifact.')
            remote_digest.update(chunk)
    if size != record['bytes'] or remote_digest.hexdigest() != record['sha256']:
        raise ValueError('Public download bytes do not match the local artifact.')
    exported = {key: record[key] for key in ('version', 'build', 'minimumMacOS', 'architecture', 'file',
                                             'bytes', 'sha256', 'codeSigning', 'notarized', 'notes')}
    exported.update(schemaVersion=1, status='published', releaseDate=release['published_at'],
                    downloadURL=asset['browser_download_url'], releaseURL=release['html_url'])
    validate(exported)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(exported, ensure_ascii=False, indent=2) + '\n')
    print(f'Public artifact verified; wrote {args.output}')


if __name__ == '__main__':
    try:
        main()
    except (ValueError, KeyError, OSError, subprocess.CalledProcessError) as error:
        sys.exit(f'Release metadata failed: {error}')
